name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-linux:
    name: Linux
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go 1.x
        uses: actions/setup-go@v4
        with:
          go-version: 1.21
          check-latest: true
          cache: true
        id: go

      - name: Get dependencies
        run: |
          cd apps/example && go get -v -t -d ./...

      - name: Test
        run: |
          cd apps/example && go mod verify
          cd apps/example && go mod download
          cd apps/example && go test ./...
          cd apps/example && go build -v main.go

      - name: Codecov
        uses: codecov/codecov-action@v3
